name: Release

on:
  push:
    tags:
      - "v*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package addon
        uses: BigWigsMods/packager@v2
        with:
          args: -t FUA
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
